language: c
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - build-essential
    - m4
    - ocaml
    - ocaml-native-compilers
    - camlp4-extra
    - opam
    - aspcud
    - libgmp-dev
cache:
  apt: true
  directories:
    - $HOME/.opam
    - $HOME/.sbt
    - $HOME/.ivy2
before_cache:
  - rm -f "$HOME/.opam/log/*"
install: bash -ex .travis-install.sh
script: bash -ex .travis-script.sh
env:
  matrix:
  - FLAGS="-vv --no-depext"
