language: c
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - avsm
    packages:
    - build-essential
    - m4
    - ocaml
    - ocaml-native-compilers
    - camlp4-extra
    - opam
    - aspcud
    - libgmp-dev
    - qemu-kvm
cache:
  apt: true
  directories:
    - $HOME/.opam
    - $HOME/.sbt
    - $HOME/.ivy2
before_cache:
  - rm -rfv $HOME/.opam/log
install: bash -ex .travis-install.sh
script: bash -ex .travis-script.sh
notifications:
  webhooks:
    urls:
    - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHN2ZW4lM0FhNm4uZGUvJTIxQm1vQ2JOWUpVU0VLYnBKUWtPJTNBYTZuLmRl"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
